'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH ttb 1 2012-08-13 "" ""
.SH NAME
ttb \- Teletekst browser for Linux/Unix
.SH DESCRIPTION
Teletekst browser (ttb) is a desktop application to browse Teletekst pages
through its internet interface.

Teletekst browser is written by Dirk-Jan Binnema with help others.  Bug
reports and requests can be sent to \fBdjcb@djcbsoftware.nl\fR.

.SH COPYRIGHT
This manual page was written by Johnny Mast
<\*(T<rave@rosiello.org\*(T>> for the
Ubuntu system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License,
Version 2 or any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in
\*(T<\fI/usr/share/common\-licenses/GPL\fR\*(T>.
